export default {
  'United States Of America': 'US',
  Andorra: 'AD',
  Anguilla: 'AI',
  Argentina: 'AR',
  Australia: 'AU',
  Austria: 'AT',
  Azerbaijan: 'AZ',
  Bahamas: 'BS',
  Bahrain: 'BH',
  Barbados: 'BB',
  Belgium: 'BE',
  Bermuda: 'BM',
  Brazil: 'BR',
  Bulgaria: 'BG',
  Canada: 'CA',
  Chile: 'CL',
  China: 'CN',
  Colombia: 'CO',
  'Costa Rica': 'CR',
  Croatia: 'HR',
  Cyprus: 'CY',
  'Czech Republic': 'CZ',
  Denmark: 'DK',
  'Dominican Republic': 'DO',
  Ecuador: 'EC',
  Estonia: 'EE',
  'Faroe Islands': 'FO',
  Finland: 'FI',
  France: 'FR',
  Georgia: 'GE',
  Germany: 'DE',
  Ghana: 'GH',
  Gibraltar: 'GI',
  'Great Britain': 'GB',
  Greece: 'GR',
  'Hong Kong': 'HK',
  Hungary: 'HU',
  Iceland: 'IS',
  India: 'IN',
  Ireland: 'IE',
  Israel: 'IL',
  Italy: 'IT',
  Jamaica: 'JM',
  Japan: 'JP',
  'Korea, Republic of': 'KR',
  Latvia: 'LV',
  Lebanon: 'LB',
  Lithuania: 'LT',
  Luxembourg: 'LU',
  Malaysia: 'MY',
  Malta: 'MT',
  Mexico: 'MX',
  Monaco: 'MC',
  Montenegro: 'ME',
  Morocco: 'MA',
  Netherlands: 'NL',
  'Netherlands Antilles': 'AN',
  'New Zealand': 'NZ',
  'Northern Ireland': 'ND',
  Norway: 'NO',
  Peru: 'PE',
  Poland: 'PL',
  Portugal: 'PT',
  Romania: 'RO',
  'Russian Federation': 'RU',
  'Saint Lucia': 'LC',
  'Saudi Arabia': 'SA',
  Serbia: 'RS',
  Singapore: 'SG',
  Slovakia: 'SK',
  Slovenia: 'SI',
  'South Africa': 'ZA',
  Spain: 'ES',
  Sweden: 'SE',
  Switzerland: 'CH',
  Taiwan: 'TW',
  Thailand: 'TH',
  'Trinidad and Tobago': 'TT',
  Turkey: 'TR',
  Ukraine: 'UA',
  'United Arab Emirates': 'AE',
  Uruguay: 'UY',
  Venezuela: 'VE',
};
