export default {
  mainContent: document.querySelector('#main-content'),
  input: document.querySelector('.search-form__input-js'),
  selected: document.querySelector('.selected'),
  optionsContainer: document.querySelector('.options__container'),
  optionsList: document.querySelectorAll('.option'),
  body: document.querySelector('.body__bg'),
  modal: document.querySelector('.modal'),
  backdrop: document.querySelector('.backdrop'),
  closeModalBtn: document.querySelector('[data-action="data-modal-close"]'),
  eventsList: document.querySelector('.events'),
  mask: document.querySelector('.mask'),
  pagination: document.querySelector('.tui-pagination'),
  footer: document.querySelector('.footer'),
  toUp: document.querySelector('.back_to_top'),
  optionsWrapper: document.querySelector('.options-wrapper'),
  form: document.querySelector('.search-form'),
  footerText: document.querySelector('.footer-container'),
};
